ES6 support + fixed controls, album, lyrics...
thiagoribeir015/spotify-control-chrome-extension pull request #11
Opened 2018-11-25 18:53 UTC by lodi-g

Fixed the extension (mostly just selectors were wrong).

Also changed the logic to query lyrics, unfortunately the old API was uh quite Brazilian only. I think Genius.com is larger and offers more diversity.

Implemented a quick & dirty backend here: https://gitlab.com/lodi-g/spotify-control-chrome-extension-backend (using gitlab for ci/cd) to protect the accessToken and avoid spamming the api.

Lmk if needs anything.

2018-11-25 18:56 UTC, lodi-g commented
Fixes #7 #8 #9

2018-11-27 09:51 UTC, thiagoribeir015 requested changes
Hey, it looks great, thanks a lot for that!

Can you please change the refs to this github project and we'll be good to merge and release a new version :)

2018-11-27 09:51 UTC, thiagoribeir015 commented on js/main.js
> +      'Unknown error, feel free to open an issue on GitHub: https://github.com/lodi-g/spotify-control-chrome-extension',
hey, I'm glad to get this merged and then release a new version of the extension asap... can you please update the references from your github to mine across your changes? I'd like to keep all issues at the same place.

2018-11-27 10:10 UTC, merged

2018-11-27 10:38 UTC, lodi-g commented
Done!

2018-11-27 10:53 UTC, thiagoribeir015 commented
hey @lodi-g new version has been published! thanks a lot for collaborating! 4.5k users are happier now :)